import Header from "@/component/Shared/Header";
import "./globals.css";
import { Container } from "@/component/UI/Container";
import ApolloClientPage from "@/component/ApolloClient/ApolloClient";

export const metadata = {
  title: "CodeNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          <ApolloClientPage>{children}</ApolloClientPage>
        </Container>
      </body>
    </html>
  );
}
