import Header from "@/component/Shared/Header";
import "./globals.css";
import { Container } from "@/component/UI/Container";

export const metadata = {
  title: "CodeNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
